FROM python:3.13-bullseye
WORKDIR /app

RUN apt-get update && apt-get install -y curl build-essential && rm -rf /var/lib/apt/lists/*
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"


COPY ml/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

WORKDIR /app/ml

RUN maturin build --release --out ../target/wheels


WORKDIR /app
RUN pip install --no-cache-dir target/wheels/*.whl

CMD ["python", "svm.py"]