[package]
name = "qsim"
version = "0.1.0"
edition = "2024"

[dependencies]
num-complex = { version = "0.4.3", features = ["serde"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }