# QuantumWorkflow Custom Resource Definition (CRD)
# Version: v0.1 (Milestone 1.1)
# This CRD defines the `QuantumWorkflow` resource, which allows users to
# declare a series of computational tasks to be orchestrated by the qflow-operator.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # The name must be in the format: <plural>.<group>
  name: quantumworkflows.qflow.io
spec:
  # group is a unique identifier for your CRD. It helps avoid name collisions.
  group: qflow.io
  # versions specifies the API versions that this CRD supports.
  versions:
    - name: v1alpha1
      # served indicates that this version is enabled and should be served by the API server.
      served: true
      # storage indicates that this is the version where objects will be stored in etcd.
      storage: true
      subresources:
        status: { }
      schema:
        # openAPIV3Schema defines the validation schema for the custom resource.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Defines the desired state of the QuantumWorkflow."
              properties:
                tasks:
                  type: array
                  description: "A list of tasks to be executed in the workflow."
                  items:
                    type: object
                    required:
                      - name
                      - image
                    properties:
                      name:
                        type: string
                        description: "The unique name of the task within the workflow."
                      image:
                        type: string
                        description: "The container image to run for this task."
              required:
                - tasks
            status:
              type: object
              description: "Reports the observed state of the QuantumWorkflow."
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string
                  description: "The current phase of the workflow (e.g., Pending, Running, Succeeded, Failed)."
                conditions:
                  type: array
                  description: "A list of conditions observing the workflow's state."
                  items:
                    type: object
                    required:
                      - type
                      - status
                      - lastTransitionTime
                      - reason
                      - message
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
  # scope can be either 'Namespaced' or 'Cluster'. 'Namespaced' is standard.
  scope: Namespaced
  names:
    # plural is the name used in the API URL: /apis/<group>/<version>/<plural>
    plural: quantumworkflows
    # singular is the alias for the plural name.
    singular: quantumworkflow
    # kind is the CamelCase name used in resource manifests.
    kind: QuantumWorkflow
    # shortNames allow for shorter strings on the CLI.
    shortNames:
      - qflow