apiVersion: qflow.io/v1alpha1
kind: QuantumWorkflow
metadata:
  name: my-quantum-workflow
spec:
  tasks:
    - name: run-bell-state
      quantum:
        image: docker.io/library/qsim:latest
        circuit: |-
          // Bell State Circuit
          OPENQASM 2.0;
          include "qelib1.inc";
          qreg q[2];
          creg c[2];
          h q[0];
          cx q[0],q[1];
          measure q[0] -> c[0];
          measure q[1] -> c[1];
        params: |-
          {
            "shots": 8192,
            "noise_model": "ideal"
          }